spring:
  application:
    name: ebank

  datasource:
    url: jdbc:h2:mem:bank
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  swagger-ui:
    path: /swagger-ui

security:
  jwt:
    secret-key: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-time: 86400000
    algorithm: HS512